/**
 * Candidate Analytics Catalog (GSC + GA4)
 *
 * Planning-only list of metrics and dimensions we can pull (or derive) for client
 * dashboards. Nothing here is wired into sync/read APIs until product picks a set.
 *
 * How to use:
 * 1. Review each entry with product/ops.
 * 2. Mark `decision` → "include" | "defer" | "skip".
 * 3. Promote included keys into `constants.ts` + models + sync.
 *
 * Sources:
 * - GSC Search Analytics API (search type `web` by default)
 * - GA4 Data API (`runReport` metrics / dimensions)
 * - Derived = computed from stored rows (not a raw Google field)
 */

export const ANALYTICS_CATALOG_DECISIONS = ["undecided", "include", "defer", "skip"] as const;
export type TAnalyticsCatalogDecision = (typeof ANALYTICS_CATALOG_DECISIONS)[number];

export const ANALYTICS_CATALOG_SOURCES = ["gsc", "ga4", "derived"] as const;
export type TAnalyticsCatalogSource = (typeof ANALYTICS_CATALOG_SOURCES)[number];

export const ANALYTICS_CATALOG_KINDS = ["metric", "dimension", "breakdown"] as const;
export type TAnalyticsCatalogKind = (typeof ANALYTICS_CATALOG_KINDS)[number];

export const ANALYTICS_CATALOG_CATEGORIES = [
  "search_performance",
  "traffic_volume",
  "acquisition",
  "engagement",
  "content",
  "geography_device",
  "conversions",
  "technical_quality",
] as const;
export type TAnalyticsCatalogCategory = (typeof ANALYTICS_CATALOG_CATEGORIES)[number];

export type TAnalyticsCatalogEntry = {
  /** Stable product id (use this when selecting include/skip). */
  id: string;
  kind: TAnalyticsCatalogKind;
  source: TAnalyticsCatalogSource;
  category: TAnalyticsCatalogCategory;
  /** Title Case label for UI discussions. */
  label: string;
  /** Google API field name, or formula note for derived. */
  apiField: string;
  /** Why a client cares. */
  clientValue: string;
  /** True if already synced/shown in Module 8 v1. */
  inV1: boolean;
  decision: TAnalyticsCatalogDecision;
  notes?: string;
};

/**
 * Full candidate set. Default `decision` is `undecided` except items already in v1
 * (`include`) so the review starts from a clear baseline.
 */
export const ANALYTICS_METRIC_CATALOG = [
  // ─── Search Console — core performance ───────────────────────────────────
  {
    id: "gsc.clicks",
    kind: "metric",
    source: "gsc",
    category: "search_performance",
    label: "Organic Clicks",
    apiField: "clicks",
    clientValue: "How Often Searchers Click Through To The Site From Google.",
    inV1: true,
    decision: "include",
  },
  {
    id: "gsc.impressions",
    kind: "metric",
    source: "gsc",
    category: "search_performance",
    label: "Impressions",
    apiField: "impressions",
    clientValue: "How Often The Site Appears In Google Search Results.",
    inV1: true,
    decision: "include",
  },
  {
    id: "gsc.ctr",
    kind: "metric",
    source: "gsc",
    category: "search_performance",
    label: "Click-Through Rate (CTR)",
    apiField: "ctr",
    clientValue: "Share Of Impressions That Become Clicks — Title/Meta Quality Signal.",
    inV1: true,
    decision: "include",
  },
  {
    id: "gsc.position",
    kind: "metric",
    source: "gsc",
    category: "search_performance",
    label: "Average Position",
    apiField: "position",
    clientValue: "Typical Ranking Depth In Results (Lower Is Better).",
    inV1: true,
    decision: "include",
    notes: "Prefer Impression-Weighted Average Across Ranges.",
  },

  // ─── Search Console — dimensions / breakdowns ────────────────────────────
  {
    id: "gsc.dim.query",
    kind: "breakdown",
    source: "gsc",
    category: "search_performance",
    label: "Top Queries (Keywords)",
    apiField: "query",
    clientValue: "Which Search Terms Drive Visibility And Clicks.",
    inV1: true,
    decision: "include",
  },
  {
    id: "gsc.dim.page",
    kind: "breakdown",
    source: "gsc",
    category: "content",
    label: "Top Pages (Search)",
    apiField: "page",
    clientValue: "Which URLs Win Organic Clicks And Impressions.",
    inV1: true,
    decision: "include",
  },
  {
    id: "gsc.dim.country",
    kind: "breakdown",
    source: "gsc",
    category: "geography_device",
    label: "Search By Country",
    apiField: "country",
    clientValue: "Where Organic Demand Comes From Geographically.",
    inV1: true,
    decision: "include",
    notes: "Stored In v1 Dimension Rows; Not Always Surfaced In UI Tables.",
  },
  {
    id: "gsc.dim.device",
    kind: "breakdown",
    source: "gsc",
    category: "geography_device",
    label: "Search By Device",
    apiField: "device",
    clientValue: "Mobile Vs Desktop Vs Tablet Search Performance.",
    inV1: true,
    decision: "include",
    notes: "Stored In v1; UI Table Optional.",
  },
  {
    id: "gsc.dim.date",
    kind: "dimension",
    source: "gsc",
    category: "search_performance",
    label: "Search By Date",
    apiField: "date",
    clientValue: "Daily Trend Lines For Clicks, Impressions, CTR, Position.",
    inV1: true,
    decision: "include",
    notes: "Powers Daily Totals; Not A Client-Facing Dimension Table.",
  },
  {
    id: "gsc.dim.searchAppearance",
    kind: "breakdown",
    source: "gsc",
    category: "search_performance",
    label: "Search Appearance",
    apiField: "searchAppearance",
    clientValue: "Rich Results / Appearance Types (When Eligible) Affecting Visibility.",
    inV1: false,
    decision: "undecided",
    notes: "Sparse For Many Sites; Higher API Cost.",
  },
  {
    id: "gsc.searchType.image",
    kind: "metric",
    source: "gsc",
    category: "search_performance",
    label: "Image Search Performance",
    apiField: "searchType=image",
    clientValue: "Useful For Visual/Ecommerce Brands Ranking In Image Results.",
    inV1: false,
    decision: "undecided",
    notes: "Separate Report Pass From Web Search.",
  },
  {
    id: "gsc.searchType.video",
    kind: "metric",
    source: "gsc",
    category: "search_performance",
    label: "Video Search Performance",
    apiField: "searchType=video",
    clientValue: "Useful When Video Content Is A Primary Acquisition Channel.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "gsc.searchType.news",
    kind: "metric",
    source: "gsc",
    category: "search_performance",
    label: "News Search Performance",
    apiField: "searchType=news",
    clientValue: "Relevant For Publishers And News-Heavy Domains.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "gsc.dim.query_page",
    kind: "breakdown",
    source: "gsc",
    category: "search_performance",
    label: "Query × Page Matrix",
    apiField: "query + page",
    clientValue: "Exact Keyword-To-URL Mapping For Content Optimization.",
    inV1: false,
    decision: "undecided",
    notes: "High Cardinality — Expensive Storage/Sync.",
  },

  // ─── GA4 — traffic volume ────────────────────────────────────────────────
  {
    id: "ga4.sessions",
    kind: "metric",
    source: "ga4",
    category: "traffic_volume",
    label: "Sessions",
    apiField: "sessions",
    clientValue: "Total Visits In The Period — Primary Traffic Volume KPI.",
    inV1: true,
    decision: "include",
  },
  {
    id: "ga4.totalUsers",
    kind: "metric",
    source: "ga4",
    category: "traffic_volume",
    label: "Total Users",
    apiField: "totalUsers",
    clientValue: "Unique Visitors Across The Period.",
    inV1: true,
    decision: "include",
  },
  {
    id: "ga4.newUsers",
    kind: "metric",
    source: "ga4",
    category: "traffic_volume",
    label: "New Users",
    apiField: "newUsers",
    clientValue: "First-Time Visitors — Growth / Acquisition Health.",
    inV1: true,
    decision: "include",
  },
  {
    id: "ga4.activeUsers",
    kind: "metric",
    source: "ga4",
    category: "traffic_volume",
    label: "Active Users",
    apiField: "activeUsers",
    clientValue: "Users With Engaged Activity In The Period (GA4 Standard).",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.screenPageViews",
    kind: "metric",
    source: "ga4",
    category: "traffic_volume",
    label: "Views (Page / Screen)",
    apiField: "screenPageViews",
    clientValue: "Total Content Views — Depth Of Browsing Beyond Sessions.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.organicSessions",
    kind: "metric",
    source: "ga4",
    category: "acquisition",
    label: "Organic Sessions",
    apiField: "sessions (filtered sessionDefaultChannelGroup=Organic Search)",
    clientValue: "Traffic From Organic Search — Ties GA4 Volume To SEO Work.",
    inV1: true,
    decision: "include",
  },

  // ─── GA4 — acquisition (sources / medium / channel) ──────────────────────
  {
    id: "ga4.dim.sessionDefaultChannelGroup",
    kind: "breakdown",
    source: "ga4",
    category: "acquisition",
    label: "Traffic By Channel Group",
    apiField: "sessionDefaultChannelGroup",
    clientValue: "Organic Vs Paid Vs Direct Vs Referral Vs Social At A Glance.",
    inV1: false,
    decision: "undecided",
    notes: "High Client Value For “Where Does Traffic Come From?”.",
  },
  {
    id: "ga4.dim.sessionSource",
    kind: "breakdown",
    source: "ga4",
    category: "acquisition",
    label: "Traffic Sources",
    apiField: "sessionSource",
    clientValue: "Exact Sources (google, newsletter Domain, Partner Sites, Etc.).",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.sessionMedium",
    kind: "breakdown",
    source: "ga4",
    category: "acquisition",
    label: "Traffic Medium",
    apiField: "sessionMedium",
    clientValue: "Organic / CPC / Referral / Email / None — Campaign Type Clarity.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.sessionSourceMedium",
    kind: "breakdown",
    source: "ga4",
    category: "acquisition",
    label: "Source / Medium",
    apiField: "sessionSourceMedium",
    clientValue: "Combined Source+Medium String Clients Already Know From GA UI.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.sessionCampaignName",
    kind: "breakdown",
    source: "ga4",
    category: "acquisition",
    label: "Campaigns",
    apiField: "sessionCampaignName",
    clientValue: "Named Campaign Performance When UTM Tracking Is In Place.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.firstUserDefaultChannelGroup",
    kind: "breakdown",
    source: "ga4",
    category: "acquisition",
    label: "New Users By Channel",
    apiField: "firstUserDefaultChannelGroup",
    clientValue: "Which Channels Bring First-Time Visitors.",
    inV1: false,
    decision: "undecided",
  },

  // ─── GA4 — engagement ────────────────────────────────────────────────────
  {
    id: "ga4.engagedSessions",
    kind: "metric",
    source: "ga4",
    category: "engagement",
    label: "Engaged Sessions",
    apiField: "engagedSessions",
    clientValue: "Quality Visits (Not Bounces) — Content / UX Health.",
    inV1: true,
    decision: "include",
  },
  {
    id: "ga4.engagementRate",
    kind: "metric",
    source: "ga4",
    category: "engagement",
    label: "Engagement Rate",
    apiField: "engagementRate",
    clientValue: "Share Of Sessions That Qualify As Engaged.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.bounceRate",
    kind: "metric",
    source: "ga4",
    category: "engagement",
    label: "Bounce Rate",
    apiField: "bounceRate",
    clientValue: "Familiar KPI For Clients Coming From Universal Analytics Mental Models.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.averageSessionDuration",
    kind: "metric",
    source: "ga4",
    category: "engagement",
    label: "Average Session Duration",
    apiField: "averageSessionDuration",
    clientValue: "How Long Visitors Stay — Rough Interest Signal.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.userEngagementDuration",
    kind: "metric",
    source: "ga4",
    category: "engagement",
    label: "User Engagement Duration",
    apiField: "userEngagementDuration",
    clientValue: "Total Engaged Time On Site Across Users.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.screenPageViewsPerSession",
    kind: "metric",
    source: "ga4",
    category: "engagement",
    label: "Views Per Session",
    apiField: "screenPageViewsPerSession",
    clientValue: "Browse Depth Per Visit.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.eventsPerSession",
    kind: "metric",
    source: "ga4",
    category: "engagement",
    label: "Events Per Session",
    apiField: "eventsPerSession",
    clientValue: "Interaction Density When Key Events Are Tracked.",
    inV1: false,
    decision: "undecided",
  },

  // ─── GA4 — content ───────────────────────────────────────────────────────
  {
    id: "ga4.dim.landingPage",
    kind: "breakdown",
    source: "ga4",
    category: "content",
    label: "Landing Pages",
    apiField: "landingPage",
    clientValue: "Entry URLs That Start Sessions — SEO Landing Performance.",
    inV1: true,
    decision: "include",
  },
  {
    id: "ga4.dim.pagePath",
    kind: "breakdown",
    source: "ga4",
    category: "content",
    label: "Top Pages (On-Site)",
    apiField: "pagePath",
    clientValue: "Most Viewed Paths Regardless Of Entry Point.",
    inV1: true,
    decision: "include",
    notes: "Mapped As Dimension Type `page` In v1.",
  },
  {
    id: "ga4.dim.pageTitle",
    kind: "breakdown",
    source: "ga4",
    category: "content",
    label: "Top Pages By Title",
    apiField: "pageTitle",
    clientValue: "Human-Readable Page Names For Non-Technical Clients.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.hostName",
    kind: "breakdown",
    source: "ga4",
    category: "content",
    label: "Hostname",
    apiField: "hostName",
    clientValue: "Useful When One Property Covers Multiple Domains/Subdomains.",
    inV1: false,
    decision: "undecided",
  },

  // ─── GA4 — geography / device ────────────────────────────────────────────
  {
    id: "ga4.dim.country",
    kind: "breakdown",
    source: "ga4",
    category: "geography_device",
    label: "Traffic By Country",
    apiField: "country",
    clientValue: "Where On-Site Visitors Come From.",
    inV1: true,
    decision: "include",
  },
  {
    id: "ga4.dim.city",
    kind: "breakdown",
    source: "ga4",
    category: "geography_device",
    label: "Traffic By City",
    apiField: "city",
    clientValue: "Local SEO / Geo-Targeted Campaign Insight.",
    inV1: false,
    decision: "undecided",
    notes: "Higher Cardinality Than Country.",
  },
  {
    id: "ga4.dim.region",
    kind: "breakdown",
    source: "ga4",
    category: "geography_device",
    label: "Traffic By Region",
    apiField: "region",
    clientValue: "State/Province Level Demand.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.deviceCategory",
    kind: "breakdown",
    source: "ga4",
    category: "geography_device",
    label: "Device Category",
    apiField: "deviceCategory",
    clientValue: "Desktop / Mobile / Tablet Mix For UX Priorities.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.operatingSystem",
    kind: "breakdown",
    source: "ga4",
    category: "geography_device",
    label: "Operating System",
    apiField: "operatingSystem",
    clientValue: "Secondary Device Insight; Usually Lower Priority Than Device Category.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.browser",
    kind: "breakdown",
    source: "ga4",
    category: "geography_device",
    label: "Browser",
    apiField: "browser",
    clientValue: "Useful For Debugging Rendering Issues; Rarely A Primary Client KPI.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.language",
    kind: "breakdown",
    source: "ga4",
    category: "geography_device",
    label: "Language",
    apiField: "language",
    clientValue: "Locale Mix For Multilingual Sites.",
    inV1: false,
    decision: "undecided",
  },

  // ─── GA4 — conversions / business outcomes ───────────────────────────────
  {
    id: "ga4.conversions",
    kind: "metric",
    source: "ga4",
    category: "conversions",
    label: "Conversions",
    apiField: "conversions",
    clientValue: "Counted Key Events Marked As Conversions — Business Outcome KPI.",
    inV1: false,
    decision: "undecided",
    notes: "Depends On Client GA4 Conversion Setup.",
  },
  {
    id: "ga4.keyEvents",
    kind: "metric",
    source: "ga4",
    category: "conversions",
    label: "Key Events",
    apiField: "keyEvents",
    clientValue: "Important Interactions Even When Not All Are “Conversions”.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.sessionConversionRate",
    kind: "metric",
    source: "ga4",
    category: "conversions",
    label: "Session Conversion Rate",
    apiField: "sessionConversionRate",
    clientValue: "Share Of Sessions That Convert — Funnel Efficiency.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.dim.eventName",
    kind: "breakdown",
    source: "ga4",
    category: "conversions",
    label: "Events By Name",
    apiField: "eventName",
    clientValue: "Form Submits, Clicks, Purchases — Requires Clean Event Taxonomy.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.ecommerce.purchaseRevenue",
    kind: "metric",
    source: "ga4",
    category: "conversions",
    label: "Purchase Revenue",
    apiField: "purchaseRevenue",
    clientValue: "Revenue For Ecommerce Clients With Purchase Tracking.",
    inV1: false,
    decision: "undecided",
    notes: "Only If Ecommerce Is Configured.",
  },
  {
    id: "ga4.ecommerce.transactions",
    kind: "metric",
    source: "ga4",
    category: "conversions",
    label: "Transactions",
    apiField: "transactions",
    clientValue: "Order Count For Ecommerce Properties.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "ga4.ecommerce.averagePurchaseRevenue",
    kind: "metric",
    source: "ga4",
    category: "conversions",
    label: "Average Order Value",
    apiField: "averagePurchaseRevenue",
    clientValue: "AOV For Store Performance Reviews.",
    inV1: false,
    decision: "undecided",
  },

  // ─── Derived / cross-source (client-friendly rollups) ────────────────────
  {
    id: "derived.totalTraffic",
    kind: "metric",
    source: "derived",
    category: "traffic_volume",
    label: "Total Traffic",
    apiField: "alias of ga4.sessions (or sessions + optional channel filter)",
    clientValue: "Simple Headline Number Clients Expect On A Dashboard.",
    inV1: false,
    decision: "undecided",
    notes: "Product Must Define: All Sessions Vs Organic Only.",
  },
  {
    id: "derived.organicShareOfSessions",
    kind: "metric",
    source: "derived",
    category: "acquisition",
    label: "Organic Share Of Traffic",
    apiField: "organicSessions / sessions",
    clientValue: "How Dependent The Site Is On SEO Vs Other Channels.",
    inV1: false,
    decision: "undecided",
    notes: "Needs Channel Or Organic Filter Accuracy.",
  },
  {
    id: "derived.gscToGa4ClickGap",
    kind: "metric",
    source: "derived",
    category: "search_performance",
    label: "GSC Clicks Vs GA4 Organic Sessions Gap",
    apiField: "gsc.clicks vs ga4.organicSessions",
    clientValue: "Highlights Tracking Gaps, Bot Noise, Or Cross-Domain Issues.",
    inV1: false,
    decision: "undecided",
    notes: "Numbers Rarely Match 1:1; Present As Directional.",
  },
  {
    id: "derived.periodOverPeriodClicks",
    kind: "metric",
    source: "derived",
    category: "search_performance",
    label: "Clicks Change Vs Prior Period",
    apiField: "delta(gsc.clicks)",
    clientValue: "Quick Win/Loss Story For Client Reporting.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "derived.periodOverPeriodSessions",
    kind: "metric",
    source: "derived",
    category: "traffic_volume",
    label: "Sessions Change Vs Prior Period",
    apiField: "delta(ga4.sessions)",
    clientValue: "Traffic Trend Without Opening Raw Charts.",
    inV1: false,
    decision: "undecided",
  },
  {
    id: "derived.topKeywordsSummary",
    kind: "breakdown",
    source: "derived",
    category: "search_performance",
    label: "Keywords Summary Card",
    apiField: "roll-up of gsc.dim.query",
    clientValue: "Count Of Ranking Queries + Top Movers Narrative.",
    inV1: false,
    decision: "undecided",
  },

  // ─── Technical / quality (optional, often deferred) ──────────────────────
  {
    id: "gsc.urlInspection",
    kind: "metric",
    source: "gsc",
    category: "technical_quality",
    label: "URL Inspection / Index Status",
    apiField: "URL Inspection API",
    clientValue: "Index Coverage Per URL — Technical SEO Deep Dive.",
    inV1: false,
    decision: "undecided",
    notes: "Different API + Quota Model; Out Of Sync Pipeline Scope.",
  },
  {
    id: "ga4.dim.landingPagePlusQueryString",
    kind: "breakdown",
    source: "ga4",
    category: "technical_quality",
    label: "Landing Page + Query String",
    apiField: "landingPagePlusQueryString",
    clientValue: "Debug UTM/Param Noise; Rarely A Primary Client Report.",
    inV1: false,
    decision: "undecided",
  },
] as const satisfies readonly TAnalyticsCatalogEntry[];

export type TAnalyticsCatalogId = (typeof ANALYTICS_METRIC_CATALOG)[number]["id"];

/** Helpers for product review sessions. */
export function listCatalogByDecision(decision: TAnalyticsCatalogDecision) {
  return ANALYTICS_METRIC_CATALOG.filter((entry) => entry.decision === decision);
}

export function listCatalogByCategory(category: TAnalyticsCatalogCategory) {
  return ANALYTICS_METRIC_CATALOG.filter((entry) => entry.category === category);
}

export function listCatalogNotInV1() {
  return ANALYTICS_METRIC_CATALOG.filter((entry) => !entry.inV1);
}
